 
 /*------------------------------------------------------------------------
    File        : ddd
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : dpachipu
    Created     : Wed May 24 19:24:37 IST 2017
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS ddd: 

END CLASS.